version: '3'

services:
  app:
    container_name: app
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8080"
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_DATABASE: app_db
      MYSQL_USER: dollar
      MYSQL_PASSWORD: dollar_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
volumes:
  dbdata:
